"""add unique constraint on stores chain external_id

Revision ID: 22473bbb24ad
Revises: 77679fca8dbd
Create Date: 2026-08-21 17:15:40.864139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22473bbb24ad'
down_revision: Union[str, Sequence[str], None] = '77679fca8dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_store_chain_external_id', ['chain', 'external_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_constraint('uq_store_chain_external_id', type_='unique')

    # ### end Alembic commands ###
