"""add scan_history table

Revision ID: 45d8eea8ba92
Revises: 22473bbb24ad
Create Date: 2026-08-22 12:30:46.158684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d8eea8ba92'
down_revision: Union[str, Sequence[str], None] = '22473bbb24ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ean', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('nutriscore_grade', sa.String(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_history_scanned_at'), ['scanned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_scan_history_scanned_at'))

    op.drop_table('scan_history')
    # ### end Alembic commands ###
