"""add fuel_stations table

Revision ID: 77679fca8dbd
Revises: d268a8a50a27
Create Date: 2026-08-20 17:26:57.877759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77679fca8dbd'
down_revision: Union[str, Sequence[str], None] = 'd268a8a50a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('gasoleo_a', sa.Float(), nullable=True),
    sa.Column('gasolina_95_e5', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_stations_external_id'), ['external_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_stations_external_id'))

    op.drop_table('fuel_stations')
    # ### end Alembic commands ###
