"""add canonical_category to products

Revision ID: d268a8a50a27
Revises: 1492bd8fbcc3
Create Date: 2026-08-20 16:32:40.910349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd268a8a50a27'
down_revision: Union[str, Sequence[str], None] = '1492bd8fbcc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canonical_category', sa.String(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_products_top_category'))
        batch_op.create_index(batch_op.f('ix_products_canonical_category'), ['canonical_category'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_canonical_category'))
        batch_op.create_index(batch_op.f('ix_products_top_category'), ['top_category'], unique=False)
        batch_op.drop_column('canonical_category')

    # ### end Alembic commands ###
